<h1>Machine learning Assignment Jesan ale<h1>

<h2>Iris database - Nearest neighbour algorithm<h2>

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
import numpy as np
import math

#Loading database
iris = load_iris()

#Splitting into training and test (Default 3:1 ratio)
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, random_state=2406)
print (len (X_train),len (X_test))
print (len (Y_train),len (Y_test))

112 38
112 38


In [2]:
#Eulidian distance
#Long ver
# def dist(p1,p2):
#     total=0
#     for n in range (len(p1)):
#         total=total+(p2[n]-p1[n])**2
#     return total**(1/2)

#Simplified
def dist(p1, p2):
    return np.sqrt(np.sum((p1 - p2) ** 2))   

In [3]:
#Loop through training set using X_test set as an index
error=0
for y in range (len(X_test)):
    #Store min val
    small=1000000
    #print ("[",x,"]")    #Testing for inner loop through X_training
    for x in range (len(X_train)):
        temp = dist(X_train[x],X_test[y])
        #Store min val
        if temp < small: 
            small=temp
            pred=Y_train[x]
    if pred != Y_test[y]:
        error=error+1
        
    print ("[",y,"]","Distance for",X_test[y], "=", small, iris['target_names'][pred])
print ("Error rate =",error,"/",len(X_test))

[ 0 ] Distance for [7.9 3.8 6.4 2. ] = 0.4123105625617661 virginica
[ 1 ] Distance for [4.7 3.2 1.3 0.2] = 0.14142135623730978 setosa
[ 2 ] Distance for [6.5 2.8 4.6 1.5] = 0.24494897427831766 versicolor
[ 3 ] Distance for [4.3 3.  1.1 0.1] = 0.3162277660168382 setosa
[ 4 ] Distance for [6.1 2.6 5.6 1.4] = 0.5567764362830022 versicolor
[ 5 ] Distance for [4.7 3.2 1.6 0.2] = 0.1414213562373093 setosa
[ 6 ] Distance for [5.1 3.4 1.5 0.2] = 0.09999999999999964 setosa
[ 7 ] Distance for [5.7 4.4 1.5 0.4] = 0.3605551275463992 setosa
[ 8 ] Distance for [7.2 3.6 6.1 2.5] = 0.6324555320336759 virginica
[ 9 ] Distance for [7.2 3.2 6.  1.8] = 0.3464101615137756 virginica
[ 10 ] Distance for [6.3 2.9 5.6 1.8] = 0.24494897427831802 virginica
[ 11 ] Distance for [6.7 3.1 4.7 1.5] = 0.2828427124746193 versicolor
[ 12 ] Distance for [6.2 2.2 4.5 1.5] = 0.26457513110645864 versicolor
[ 13 ] Distance for [6.7 3.3 5.7 2.5] = 0.24494897427831785 virginica
[ 14 ] Distance for [6.8 3.  5.5 2.1] = 0.1732050

In [4]:
print(iris['target_names'][Y_test]) #Verify match

['virginica' 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'setosa'
 'setosa' 'virginica' 'virginica' 'virginica' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'setosa' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'setosa' 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa'
 'virginica' 'virginica' 'setosa' 'versicolor' 'virginica' 'setosa'
 'versicolor' 'virginica' 'virginica' 'versicolor' 'virginica' 'virginica']


 <h2>Conformal predictor<h2>

In [5]:
#Vector containing p values
p=np.arange(38)

for a in range (len(X_test)):
    #Store min val
    same=1000000
    diff=1000000
    #print ("[",x,"]")
    for b in range (len(X_train)):
        temp = dist(X_train[b],X_test[a])
        #if same type
        if [Y_test[a]]==[Y_train[b]]:
            #print ("Match",[Y_test[a]],[Y_train[b]], "distance =", temp)
            if temp < same: 
                same=temp
        #if different type
        else:
            #if temp < 2: print ("Match",[Y_test[a]],[Y_train[b]], "distance =", temp)
            if temp < diff: 
                diff=temp
     #Exceptions for 0 div
    if same ==0 and diff==0:
        p[a]==0
    elif same==0 and diff>0:
        p[a]==np.inf
    else:
        p[a]=diff/same           
    
p

array([ 4, 14,  1,  7,  0, 13, 19,  7,  2,  3,  2,  2,  2,  5,  4,  8,  6,
        5,  5,  8, 14, 14, 13,  6, 14,  6,  3,  1,  9,  1,  1, 14,  2,  1,
        8,  3,  3,  2])

In [6]:
def falsep (bid):
    a=np.arange(len(bid))
    for n in range (len(bid)): #Loop thorugh p values
        a[n] = np.mean(np.delete(bid, n)) #Take mean of P values minus true label
    return np.mean(a) #Return average of averages

In [7]:
#Average false p-value for the Nearest Neighbour conformal predictor applied to the iris dataset
falsep(p)

5.7894736842105265

<h2>Ionosphere - Nearest neighbour algorithm<h2>

In [8]:
#Import and find total samples
ion = np.genfromtxt("ionosphere.txt", delimiter=",")
print (len(ion))

351


In [9]:
#Store data and labels in seperate variables
label = np.genfromtxt("ionosphere.txt", delimiter=",", usecols=34, dtype='int') #34 Features removed
data = np.genfromtxt("ionosphere.txt", delimiter=",", usecols=[*range(0,34)], dtype='float')
#Splitting into training and test (Default 3:1 ratio)
V_train, V_test, W_train, W_test = train_test_split(data, label, random_state=2406)

In [10]:
print (len (V_train),len (V_test))
print (len (W_train),len (W_test))

263 88
263 88


In [11]:
#Double check with .txt file
print (V_train[:3])
print (W_train[:3])

[[ 1.       0.       0.46785  0.11308  0.5898   0.00665  0.55432  0.06874
   0.47894 -0.13969  0.52993  0.0133   0.63858 -0.16186  0.67849 -0.03326
   0.54545 -0.13525  0.52993 -0.04656  0.47894 -0.19512  0.50776 -0.13525
   0.41463 -0.20177  0.5393  -0.11455  0.59867 -0.02882  0.53659 -0.11752
   0.56319 -0.04435]
 [ 0.       0.      -1.       1.       1.      -1.       0.       0.
   0.       0.       1.      -1.       1.       1.       0.       0.
   1.      -1.       0.       0.       0.       0.       1.       1.
  -1.       1.       1.      -1.      -1.       1.      -1.      -1.
   0.       0.     ]
 [ 1.       0.       1.      -0.16316  1.      -0.10169  0.99999 -0.15197
   1.      -0.19277  0.94055 -0.35151  0.95735 -0.29785  0.93719 -0.34412
   0.94486 -0.28106  0.90137 -0.43383  0.86043 -0.47308  0.82987 -0.5122
   0.8408  -0.47137  0.76224 -0.5837   0.65723 -0.68794  0.68714 -0.64537
   0.64727 -0.67226]]
[ 1 -1  1]


In [12]:
print (V_test[:1])

[[ 1.       0.       0.39286  0.52381 -0.78824  0.11342 -0.16628 -0.76378
   0.66667  0.0119   0.82143  0.40476 -0.6723   0.30729 -0.34797 -0.63668
   0.46429  0.15476  0.54762  0.05952 -0.5183   0.44961 -0.47651 -0.47594
   0.32143  0.70238  0.51971  0.38848  0.57143  0.39286 -0.54891 -0.29915
   0.25441 -0.55837]]


In [13]:
#Loop through training set 
error=0
for c in range (len(V_test)):
    #Store min val
    small=1000000
    for d in range (len(V_train)):
        #print ("[",d,"]")    #Nested loop
        temp = dist(V_train[d],V_test[c])
        #Store min val
        if temp < small: 
            small=temp
            guess=W_train[d]
    if guess != W_test[c]:
        error=error+1
        
    print ("[",c,"]","Distance for",V_test[c][:3], "=", small,"Class:", guess)
print ("Error rate =", error,"/",len(V_test))

[ 0 ] Distance for [1.      0.      0.39286] = 2.5572304692968135 Class: -1
[ 1 ] Distance for [1.      0.      0.97588] = 0.8236918435920074 Class: 1
[ 2 ] Distance for [0. 0. 1.] = 3.8543699093755905 Class: 1
[ 3 ] Distance for [1.      0.      0.75564] = 0.6968197246060132 Class: 1
[ 4 ] Distance for [1.      0.      0.95202] = 0.18367406975400746 Class: 1
[ 5 ] Distance for [1.      0.      0.88853] = 0.20386311927369308 Class: 1
[ 6 ] Distance for [1.      0.      0.91241] = 0.2529501180074838 Class: 1
[ 7 ] Distance for [0. 0. 0.] = 3.65181885899342 Class: -1
[ 8 ] Distance for [1. 0. 1.] = 3.0987629611023815 Class: -1
[ 9 ] Distance for [1.      0.      0.82624] = 0.3697898208442195 Class: 1
[ 10 ] Distance for [1.     0.     0.8941] = 0.4086475498519476 Class: 1
[ 11 ] Distance for [1. 0. 1.] = 1.2694126662358463 Class: 1
[ 12 ] Distance for [1.   0.   0.25] = 0.3469841094344235 Class: 1
[ 13 ] Distance for [1. 0. 1.] = 1.3706818319362084 Class: 1
[ 14 ] Distance for [1. 0. 1.]

In [14]:
print(W_test)

[-1  1 -1  1  1  1  1 -1 -1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1 -1
 -1 -1  1 -1  1  1  1 -1  1  1 -1  1 -1  1  1  1  1  1 -1  1  1  1  1  1
 -1  1 -1  1 -1  1  1 -1 -1  1  1  1 -1  1 -1  1 -1  1  1 -1  1 -1 -1 -1
  1  1 -1 -1  1  1  1 -1  1  1  1  1  1  1  1 -1]


In [15]:
print(W_train)

[ 1 -1  1  1 -1  1  1 -1  1 -1  1  1 -1  1  1  1  1  1 -1  1  1  1  1  1
  1  1  1  1  1 -1  1 -1  1  1  1 -1  1 -1  1 -1  1 -1 -1  1  1 -1  1  1
  1 -1 -1  1  1 -1 -1  1 -1 -1  1 -1  1 -1  1  1 -1  1 -1 -1 -1 -1  1  1
  1  1  1  1  1  1 -1  1  1  1  1 -1  1  1  1 -1 -1  1  1 -1 -1  1  1  1
  1  1  1  1  1  1  1  1  1 -1  1 -1  1  1  1  1  1  1 -1 -1  1 -1  1  1
 -1  1  1 -1  1  1  1  1  1 -1 -1 -1 -1  1  1 -1  1 -1  1  1  1  1 -1 -1
  1  1 -1  1 -1  1 -1  1  1 -1 -1 -1  1  1  1 -1  1  1 -1 -1  1 -1 -1  1
  1 -1  1  1  1  1  1  1 -1 -1 -1  1  1 -1  1  1 -1  1  1  1 -1 -1  1  1
 -1 -1 -1  1  1 -1  1  1  1 -1 -1  1  1  1 -1  1  1  1  1 -1  1  1 -1 -1
 -1 -1  1  1  1 -1 -1  1  1  1  1 -1 -1  1  1 -1  1  1  1 -1 -1  1  1  1
  1 -1 -1 -1 -1  1  1  1  1  1  1 -1  1  1 -1 -1 -1  1  1 -1  1  1 -1]


<h2>Conformal predictor<h2>

In [16]:
#Vector containing p values
p2=np.arange(88)

for e in range (len(V_test)):
    #Store min val
    same=100
    diff=100
    for f in range (len(V_train)):
        temp = dist(V_train[f],V_test[e])
        #if same type
        if [W_test[e]]==[W_train[f]]:
            #print (f,"Match",[W_test[e]],[W_train[f]], "distance =", temp)
            if temp < same: 
                same=temp
        #if different type
        else:
            #if temp < 2: print ("Match",[W_test[e]],[W_train[f]], "distance =", temp)
            if temp < diff: 
                diff=temp
                
       #Exceptions for 0 div
    if same ==0 and diff==0:
        p2[e]==0
    elif same==0 and diff>0:
        p2[e]==np.inf
    else:
        p2[e]=diff/same           

In [17]:
#P values
p2

array([ 1,  2,  0,  3,  9,  6,  6,  1,  1,  4,  4,  1,  2,  2,  0,  3,  1,
        1,  3,  1,  1,  3,  8,  0,  0,  1,  3,  0,  1,  2,  8,  0,  6,  2,
        2,  2,  1,  2,  3,  8,  1,  5,  1,  1,  2,  2,  5,  1,  1,  1,  1,
        1,  0,  1,  2,  1,  0, 10,  6,  7,  1,  3, 62, 13,  0,  5,  5,  1,
        1,  1,  0,  1,  7,  1,  1,  0,  4,  1,  5,  0, 11,  2,  1,  1,  1,
        1,  2,  0])

In [24]:
def falsep (bid):
    a=np.arange(bid)
    for n in range (len(bid)): #Loop thorugh p values
        a[n] = np.mean(np.delete(bid, n)) #Take mean of P values minus true label
    return np.mean(a) #Return average of averages